### ISSUE TITLE
Javac 

### ISSUE THREAD

**Issue by Aksshay88** [Aksshay88/CIT-Management-System#1]
javac splash.java not working

**Comment by Kaarthik-07** [comment]
Super bro .. congrats it's a remarkable achievement that you got, i am very proud of you!!!!

**Comment by ChristuRufina** [comment]
Elite-level bug sniping, You're basically the John Wick of debugging, no bug is safe.....Keep going bro!!

**Comment by wisebreadloaf** [comment]
<img src="https://github.com/user-attachments/assets/8d38fcfe-b963-455e-acd8-efb164949462" alt="yo avan selai'ku avane mala podran paru ya">

**Comment by Aksshay88** [comment]
@wisebreadloaf @ChristuRufina @Kaarthik-07 Yov guys wassup?
suddenely coming up to put a chat 🙃
